language: generic
sudo: false
dist: trusty

notifications:
  email: false

env:
  matrix:
  - ARGS=""
  - ARGS="--resolver lts-9"

addons:
  apt:
    packages:
      - libgmp-dev

before_install:
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
  - stack --no-terminal --install-ghc build $ARGS --test --only-dependencies

script:
  - stack --no-terminal $ARGS build
  - stack --no-terminal $ARGS test
  - stack --no-terminal $ARGS haddock --no-haddock-deps
  - stack --no-terminal $ARGS sdist

cache:
  directories:
    - $HOME/.stack
